on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

name: Build Project

jobs:
  test:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Check for errors
        run: flutter analyze

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Build APK
        run: flutter build apk --release

      - name: Build App Bundle
        run: flutter build appbundle --release

      - name: Upload Artifact (Android APK)
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Artifact (Android App Bundle)
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Build Windows
        run: flutter build windows --release

      - name: Create ZIP
        run: |
          Copy-Item "build/windows/x64/runner/Release" -Destination "FarmaStock-${{github.ref_name}}" -Recurse
          Compress-Archive -Path "FarmaStock-${{github.ref_name}}" -Destination windows.zip

      - name: Upload Artifact (Windows ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: windows-zip
          path: windows.zip

  build-linux:
    name: Build Linux
    runs-on: ubuntu-22.04
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Install Linux dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Build Linux
        run: flutter build linux --release

      - name: Create ZIP
        run: |
          cp -r "build/linux/x64/release/bundle" "FarmaStock-${{github.ref_name}}"
          zip -r linux.zip "FarmaStock-${{github.ref_name}}"

      - name: Upload Artifact (Linux ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: linux-zip
          path: linux.zip

  build-web:
    name: Build Web
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Build Web
        run: flutter build web --release

      - name: Create ZIP
        run: |
          cd build/web
          zip -r ../../web.zip .

      - name: Upload Artifact (Web ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: web-zip
          path: web.zip

  build-github-pages:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.0
          cache: true

      - name: Build Web
        run: |
          REPO_NAME=${GITHUB_REPOSITORY##*/}
          flutter build web --release --base-href "/$REPO_NAME/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-android
      - build-windows
      - build-linux
      - build-web
    steps:
      - name: Download Artifact (Android APK)
        uses: actions/download-artifact@v4
        with:
          name: android-apk

      - name: Download Artifact (Android App Bundle)
        uses: actions/download-artifact@v4
        with:
          name: android-appbundle

      - name: Download Artifact (Windows ZIP)
        uses: actions/download-artifact@v4
        with:
          name: windows-zip

      - name: Download Artifact (Linux ZIP)
        uses: actions/download-artifact@v4
        with:
          name: linux-zip

      - name: Download Artifact (Web ZIP)
        uses: actions/download-artifact@v4
        with:
          name: web-zip

      - name: Rename Artifacts
        run: |
          mv app-release.apk FarmaStock-${{github.ref_name}}-android.apk
          mv app-release.aab FarmaStock-${{github.ref_name}}-android.aab
          mv windows.zip FarmaStock-${{github.ref_name}}-windows.zip
          mv linux.zip FarmaStock-${{github.ref_name}}-linux.zip
          mv web.zip FarmaStock-${{github.ref_name}}-web.zip

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ## Downloads

            [![Web](https://img.shields.io/badge/Web-258ffa?style=for-the-badge&logo=html5&logoColor=white)](https://github.com/josejefferson/farmastock/releases/download/${{github.ref_name}}/FarmaStock-${{github.ref_name}}-web.zip)
            [![Android](https://img.shields.io/badge/Android-3DDC84?style=for-the-badge&logo=android&logoColor=white)](https://github.com/josejefferson/farmastock/releases/download/${{github.ref_name}}/FarmaStock-${{github.ref_name}}-android.apk)
            [![Windows](https://img.shields.io/badge/Windows-0078D6?style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0ODc1IDQ4NzUiPjxwYXRoIGZpbGw9IiNmZmYiIGQ9Ik0wIDBoMjMxMXYyMzEwSDB6bTI1NjQgMGgyMzExdjIzMTBIMjU2NHpNMCAyNTY0aDIzMTF2MjMxMUgwem0yNTY0IDBoMjMxMXYyMzExSDI1NjQiLz48L3N2Zz4=&logoColor=white)](https://github.com/josejefferson/farmastock/releases/download/${{github.ref_name}}/FarmaStock-${{github.ref_name}}-windows.zip)
            [![Linux](https://img.shields.io/badge/Linux-FCC624?style=for-the-badge&logo=linux&logoColor=black)](https://github.com/josejefferson/farmastock/releases/download/${{github.ref_name}}/FarmaStock-${{github.ref_name}}-linux.zip)
          files: |
            ./FarmaStock-${{github.ref_name}}-android.apk
            ./FarmaStock-${{github.ref_name}}-android.aab
            ./FarmaStock-${{github.ref_name}}-windows.zip
            ./FarmaStock-${{github.ref_name}}-linux.zip
            ./FarmaStock-${{github.ref_name}}-web.zip
          fail_on_unmatched_files: true
          prerelease: ${{endsWith(github.ref_name, '-beta')}}
